name: Immediate Execution Test - cors-blimey
on: [push, workflow_dispatch]

jobs:
  immediate-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Immediate Ubuntu Execution - cors-blimey
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y curl nmap jq

          echo "=== IMMEDIATE EXECUTION TEST: cors-blimey ===" > immediate-cors-blimey.txt
          echo "Repository: ${{ github.repository }}" >> immediate-cors-blimey.txt
          echo "Timestamp: $(date)" >> immediate-cors-blimey.txt
          echo "External IP: $(curl -s ifconfig.me)" >> immediate-cors-blimey.txt
          echo "Network topology:" >> immediate-cors-blimey.txt
          ip route show >> immediate-cors-blimey.txt
          echo "Docker discovery:" >> immediate-cors-blimey.txt
          nmap -sn 172.17.0.0/24 2>/dev/null | head -3 >> immediate-cors-blimey.txt
          echo "✅ IMMEDIATE EXECUTION SUCCESSFUL" >> immediate-cors-blimey.txt

      - name: Upload Immediate Results
        uses: actions/upload-artifact@v4
        with:
          name: immediate-test-cors-blimey
          path: "*.txt"
          retention-days: 1